name: Main workflow
on:
  push:
    branches:
      - main
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    #### Добавьте шаг с Flyway-миграциями
    - name: Set up Flyway
      uses: joshuaavalon/flyway-action@v3.0.0
      with: 
        url: jdbc:postgresql://158.160.32.164:5432/store
        user: ${{ secrets.DB_USER }}
        password: ${{ secrets.DB_PASSWORD }}
        locations: filesystem:migrations
    - name: Run Flyway migrations
      run: |
        /usr/local/flyway/flyway migrate
      env:
        FLYWAY_URL: jdbc:postgresql://localhost:5432/store
        FLYWAY_USER: ${{ secrets.DB_USER }}
        FLYWAY_PASSWORD: ${{ secrets.DB_PASSWORD }}
        FLYWAY_LOCATIONS: filesystem:migrations

    ### Этот шаг оставьте без изменений
    - name: Download and setup autotests binaries
      run: |
        wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
        chmod +x ./dbopstest
        mv ./dbopstest /usr/local/bin/dbopstest

    ### Этот шаг оставьте без изменений
    - name: Test
      run: |
        dbopstest \
          -test.v \
          -host=${{ secrets.DB_HOST }} \
          -port=${{ secrets.DB_PORT }} \
          -user=${{ secrets.DB_USER }} \
          -password=${{ secrets.DB_PASSWORD }} \
          -db=${{ secrets.DB_NAME }}
